"""Patch interface and placeholder implementation."""

from __future__ import annotations

import difflib
import json
import logging
import re
import subprocess
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any, Optional


@dataclass
class PatchRequest:
    """Inputs consumed by the patch generation module."""

    round_id: int
    status_payload: dict[str, Any]
    metrics_payload: dict[str, Any]
    last_error_text: str
    config_file_path: Optional[Path]
    config_text: str
    git_diff: str


@dataclass
class PatchPlan:
    """Output from the patch generation module."""

    summary: str
    suggestions: list[str] = field(default_factory=list)
    patch_text: Optional[str] = None
    can_auto_apply: bool = False


@dataclass
class PatchApplyResult:
    """Record of patch apply behavior."""

    applied: bool
    patch_file: Optional[Path]
    notes_file: Optional[Path]
    message: str


class PatchAgent(ABC):
    """Contract for future LLM-backed patch agents."""

    @abstractmethod
    def generate_patch(self, request: PatchRequest) -> PatchPlan:
        raise NotImplementedError


class HeuristicPatchAgent(PatchAgent):
    """
    Placeholder patch generator.

    This class is intentionally simple. Replace `generate_patch` with real LLM calls
    without touching orchestrator logic.
    """

    def __init__(self, logger: logging.Logger, repo_path: Path) -> None:
        self.logger = logger
        self.repo_path = repo_path

    def generate_patch(self, request: PatchRequest) -> PatchPlan:
        status = str(request.status_payload.get("status", "")).lower().strip()
        error_text = (request.last_error_text or "").strip()
        summary = f"round={request.round_id}, status={status or 'unknown'}"

        if status in {"success", "succeeded", "completed", "done", "ok"}:
            return PatchPlan(
                summary=f"{summary}: previous round already succeeded, no patch generated.",
                suggestions=["No code change required."],
            )

        suggestions: list[str] = []
        patch_text: Optional[str] = None
        can_auto_apply = False

        if error_text:
            lowered_error = error_text.lower()
            if "out of memory" in lowered_error or "cuda oom" in lowered_error:
                suggestions.append("Detected OOM. Reduce batch size or image resolution.")
                candidate_patch = self._try_build_batch_size_patch(request.config_file_path, request.config_text)
                if candidate_patch:
                    patch_text = candidate_patch
                    can_auto_apply = True
                    suggestions.append("Generated a config patch that halves the first batch size it found.")
            elif "file not found" in lowered_error or "no such file" in lowered_error:
                suggestions.append("Detected missing file path. Check dataset mount path and Drive sync consistency.")
            else:
                suggestions.append("Error detected. Review last_error.txt and train.log tail for root cause.")
        else:
            suggestions.append("No explicit error text found. Check status.json freshness and train.log updates.")

        if not (request.git_diff or "").strip():
            suggestions.append("Working tree is clean before patch generation.")

        if patch_text is None:
            suggestions.append("No deterministic auto-patch generated by placeholder heuristics.")

        return PatchPlan(
            summary=summary,
            suggestions=suggestions,
            patch_text=patch_text,
            can_auto_apply=can_auto_apply,
        )

    def _try_build_batch_size_patch(self, config_path: Optional[Path], config_text: str) -> Optional[str]:
        if config_path is None or not config_text.strip():
            return None

        lines = config_text.splitlines(keepends=True)
        modified = list(lines)
        changed = False

        yaml_like_pattern = re.compile(r"^(\s*batch_size\s*:\s*)(\d+)(\s*)$", re.IGNORECASE)
        cli_like_pattern = re.compile(r"(--batch(?:_size)?\s+)(\d+)\b", re.IGNORECASE)

        for idx, line in enumerate(lines):
            m_yaml = yaml_like_pattern.match(line.rstrip("\n"))
            if m_yaml:
                old_value = int(m_yaml.group(2))
                if old_value > 1:
                    new_value = max(1, old_value // 2)
                    newline = f"{m_yaml.group(1)}{new_value}{m_yaml.group(3)}\n"
                    modified[idx] = newline
                    changed = True
                break

            m_cli = cli_like_pattern.search(line)
            if m_cli:
                old_value = int(m_cli.group(2))
                if old_value > 1:
                    new_value = max(1, old_value // 2)
                    modified[idx] = line[: m_cli.start(2)] + str(new_value) + line[m_cli.end(2) :]
                    changed = True
                break

        if not changed:
            return None

        rel = config_path
        try:
            rel = config_path.resolve().relative_to(self.repo_path.resolve())
        except ValueError:
            rel = config_path

        from_file = f"a/{rel.as_posix()}"
        to_file = f"b/{rel.as_posix()}"
        patch_lines = difflib.unified_diff(lines, modified, fromfile=from_file, tofile=to_file, lineterm="")
        patch_text = "\n".join(patch_lines) + "\n"
        return patch_text


class PatchApplier:
    """Persist patch artifacts and optionally apply generated patch."""

    def __init__(self, repo_path: Path, output_dir: Path, logger: logging.Logger) -> None:
        self.repo_path = repo_path
        self.output_dir = output_dir
        self.logger = logger
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def apply_plan(self, request: PatchRequest, plan: PatchPlan, auto_apply_enabled: bool) -> PatchApplyResult:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        prefix = f"round_{request.round_id:03d}_{timestamp}"
        notes_file = self.output_dir / f"{prefix}_notes.json"

        notes_payload = {
            "round_id": request.round_id,
            "summary": plan.summary,
            "suggestions": plan.suggestions,
            "has_patch": bool(plan.patch_text),
            "can_auto_apply": plan.can_auto_apply,
            "auto_apply_enabled": auto_apply_enabled,
        }
        notes_file.write_text(json.dumps(notes_payload, ensure_ascii=False, indent=2), encoding="utf-8")

        patch_file: Optional[Path] = None
        if plan.patch_text:
            patch_file = self.output_dir / f"{prefix}.patch"
            patch_file.write_text(plan.patch_text, encoding="utf-8")
            self.logger.info("Patch generated at %s", patch_file)

            if auto_apply_enabled and plan.can_auto_apply:
                self._apply_patch_with_git(patch_file)
                return PatchApplyResult(
                    applied=True,
                    patch_file=patch_file,
                    notes_file=notes_file,
                    message="Patch generated and auto-applied by git apply.",
                )

            return PatchApplyResult(
                applied=False,
                patch_file=patch_file,
                notes_file=notes_file,
                message="Patch generated but not auto-applied.",
            )

        return PatchApplyResult(
            applied=False,
            patch_file=None,
            notes_file=notes_file,
            message="No patch generated; notes file written.",
        )

    def _apply_patch_with_git(self, patch_file: Path) -> None:
        cmd = ["git", "apply", "--whitespace=fix", str(patch_file)]
        self.logger.info("Applying patch via git apply: %s", patch_file)
        proc = subprocess.run(
            cmd,
            cwd=self.repo_path,
            text=True,
            encoding="utf-8",
            errors="replace",
            capture_output=True,
            check=False,
        )
        if proc.returncode != 0:
            raise RuntimeError(f"git apply failed: {proc.stderr.strip()}")
